source 'https://rubygems.org'

gem 'highline'
gem 'inspec-bin'
gem 'inspec'
gem 'inspec_tools'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-puppet'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'librarian-puppet'
gem 'kitchen-ansible'
gem 'puppet'
gem 'rake'
gem 'rubocop'